lr: 0.00008347986263060389
seed: 1337
z_dim: 256

dataset: "L2D"
pooling: "meanmax"
evaluate: false
use_wandb: false
batch_size: 8
num_epochs: 5
output_dir: "./data/frame_embeddings/L2D"
pin_memory: false
wandb_mode: "online"
num_workers: 4
wandb_group: null
encoder_name: "resnet18"
pool_dropout: 0
task_weights: null
val_fraction: 0.1
wandb_entity: null
weight_decay: 0.00003494660029703862
no_pretrained: false
train_encoder: false
wandb_project: "frame_encoder_training"
num_pool_heads: 4
wandb_run_name: null
best_model_path: "./models/frame_encoder/best_model_l2d.pt"
extract_targets: false
label_smoothing: 0.05
pool_hidden_dim: 128
encoder_trainable: "partial:4"
task_head_dropout: 0
frame_head_dropout: 0.2
num_classes_per_task:
  - 5
  - 5
  - 5
  - 5
  - 5
task_head_activation: "relu"
frame_head_activation: "relu"
pool_temperature_init: 1
task_head_hidden_dims: []
frame_head_hidden_dims:
  - 512
